CREATE TABLE place_tag_catalogs
(
    id                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '장소 태그 카탈로그 식별자',
    tag_code          VARCHAR(50)  NOT NULL COMMENT '코드와 데이터 간 참조에 사용하는 변경 불가 태그 코드',
    category          VARCHAR(30)  NOT NULL COMMENT '태그 분류',
    display_name      VARCHAR(50)  NOT NULL COMMENT '사용자에게 노출하는 태그명',
    matching_keywords JSON         NOT NULL COMMENT '본문 후보 매칭 키워드 JSON 배열',
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '사용 및 노출 여부',
    sort_order        INT          NOT NULL COMMENT '관리 및 추론 후보 정렬 순서',
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 일시',
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 일시',
    PRIMARY KEY (id),
    UNIQUE INDEX idx_u_tag_code (tag_code),
    INDEX idx_category_enabled_sort_order (category, enabled, sort_order)
) COMMENT '기획자가 관리하는 장소 태그 카탈로그';

INSERT INTO place_tag_catalogs
    (tag_code, category, display_name, matching_keywords, enabled, sort_order)
VALUES
    ('AESTHETIC', 'ATMOSPHERE', '감성적인', CAST('["감성","감성적","감성적인","감성 가득","무드 있는"]' AS JSON), TRUE, 1),
    ('COZY', 'ATMOSPHERE', '아늑한', CAST('["아늑","아늑한","포근한","포근","cozy"]' AS JSON), TRUE, 2),
    ('QUIET', 'ATMOSPHERE', '조용한', CAST('["조용","조용한","한적한","고요한","북적이지 않는"]' AS JSON), TRUE, 3),
    ('CALM', 'ATMOSPHERE', '차분한', CAST('["차분","차분한","잔잔한","차분한 분위기"]' AS JSON), TRUE, 4),
    ('WARM', 'ATMOSPHERE', '따뜻한', CAST('["따뜻한","따스한","온화한","따뜻한 분위기"]' AS JSON), TRUE, 5),
    ('NEAT', 'ATMOSPHERE', '정갈한', CAST('["정갈","정갈한","단정한"]' AS JSON), TRUE, 6),
    ('CLEAN', 'ATMOSPHERE', '깔끔한', CAST('["깔끔","깔끔한","깨끗한","군더더기 없는"]' AS JSON), TRUE, 7),
    ('SOPHISTICATED', 'ATMOSPHERE', '세련된', CAST('["세련","세련된","모던한","모던"]' AS JSON), TRUE, 8),
    ('HIP', 'ATMOSPHERE', '힙한', CAST('["힙한","힙하다","힙한 분위기","트렌디한"]' AS JSON), TRUE, 9),
    ('VINTAGE', 'ATMOSPHERE', '빈티지한', CAST('["빈티지","빈티지한","앤틱","빈티지 무드"]' AS JSON), TRUE, 10),
    ('RETRO', 'ATMOSPHERE', '레트로한', CAST('["레트로","복고","복고풍","옛날 감성"]' AS JSON), TRUE, 11),
    ('EXOTIC', 'ATMOSPHERE', '이국적인', CAST('["이국적","이국적인","해외 느낌","외국 느낌"]' AS JSON), TRUE, 12),
    ('LUXURIOUS', 'ATMOSPHERE', '고급스러운', CAST('["고급스러운","고급진","럭셔리","우아한"]' AS JSON), TRUE, 13),
    ('CASUAL', 'ATMOSPHERE', '캐주얼한', CAST('["캐주얼","편한 분위기","부담 없는"]' AS JSON), TRUE, 14),
    ('ROMANTIC', 'ATMOSPHERE', '로맨틱한', CAST('["로맨틱","낭만적인","낭만","분위기 있는"]' AS JSON), TRUE, 15),
    ('LIVELY', 'ATMOSPHERE', '활기찬', CAST('["활기찬","활기 넘치는","생기 있는"]' AS JSON), TRUE, 16),
    ('COMFORTABLE', 'ATMOSPHERE', '편안한', CAST('["편안한","편안하게","편한 공간","편하게"]' AS JSON), TRUE, 17),
    ('DISTINCTIVE', 'ATMOSPHERE', '독특한', CAST('["독특한","특이한","개성 있는","유니크한"]' AS JSON), TRUE, 18),
    ('NATURAL', 'ATMOSPHERE', '자연스러운', CAST('["자연스러운","내추럴한","내추럴"]' AS JSON), TRUE, 19),
    ('DREAMY', 'ATMOSPHERE', '몽환적인', CAST('["몽환적","몽환적인","신비로운","dreamy"]' AS JSON), TRUE, 20),
    ('COMPACT', 'SPACE', '아담한', CAST('["아담한","아담","작은 공간","소규모"]' AS JSON), TRUE, 21),
    ('SPACIOUS', 'SPACE', '넓은', CAST('["넓은","널찍한","넓고","넓어서"]' AS JSON), TRUE, 22),
    ('PLEASANT', 'SPACE', '쾌적한', CAST('["쾌적","쾌적한","답답하지 않은"]' AS JSON), TRUE, 23),
    ('OPEN', 'SPACE', '개방적인', CAST('["개방감","개방적인","탁 트인","트여 있는"]' AS JSON), TRUE, 24),
    ('PRIVATE', 'SPACE', '프라이빗한', CAST('["프라이빗","독립된 공간","개별 공간","룸"]' AS JSON), TRUE, 25),
    ('GOOD_LIGHTING', 'SPACE', '채광 좋은', CAST('["채광","자연광","햇살 맛집","햇빛 잘 드는"]' AS JSON), TRUE, 26),
    ('GOOD_VIEW', 'SPACE', '뷰 좋은', CAST('["뷰맛집","전망 좋은","경치 좋은","뷰가 좋은"]' AS JSON), TRUE, 27),
    ('FULL_WINDOW', 'SPACE', '통창', CAST('["통창","큰 창","전면창","창이 큰"]' AS JSON), TRUE, 28),
    ('WINDOW_SEAT', 'SPACE', '창가', CAST('["창가","창가석","창가 자리"]' AS JSON), TRUE, 29),
    ('TERRACE', 'SPACE', '테라스', CAST('["테라스","테라스석","야외 테라스"]' AS JSON), TRUE, 30),
    ('ROOFTOP', 'SPACE', '루프탑', CAST('["루프탑","옥상","옥상 테라스"]' AS JSON), TRUE, 31),
    ('OUTDOOR', 'SPACE', '야외', CAST('["야외","야외석","야외 자리","외부 좌석"]' AS JSON), TRUE, 32),
    ('GARDEN', 'SPACE', '정원', CAST('["정원","가든","마당","야외 정원"]' AS JSON), TRUE, 33),
    ('HANOK', 'SPACE', '한옥', CAST('["한옥","한옥 공간","한옥 카페","고택"]' AS JSON), TRUE, 34),
    ('OCEAN_VIEW', 'SPACE', '오션뷰', CAST('["오션뷰","바다뷰","바다 보이는","바다 전망"]' AS JSON), TRUE, 35),
    ('RIVER_VIEW', 'SPACE', '리버뷰', CAST('["리버뷰","한강뷰","강뷰","강이 보이는"]' AS JSON), TRUE, 36),
    ('CITY_VIEW', 'SPACE', '시티뷰', CAST('["시티뷰","도심뷰","도시 전망","야경"]' AS JSON), TRUE, 37),
    ('FOREST_VIEW', 'SPACE', '숲뷰', CAST('["숲뷰","숲속","숲이 보이는","나무뷰"]' AS JSON), TRUE, 38),
    ('INTERIOR', 'SPACE', '인테리어', CAST('["인테리어","공간 디자인","내부 인테리어"]' AS JSON), TRUE, 39),
    ('PHOTO_ZONE', 'SPACE', '포토존', CAST('["포토존","인증샷","사진 스팟","포토스팟"]' AS JSON), TRUE, 40),
    ('DATE', 'PURPOSE', '데이트', CAST('["데이트","데이트코스","커플","데이트하기 좋은"]' AS JSON), TRUE, 41),
    ('GROUP', 'PURPOSE', '모임', CAST('["모임","단체","여러 명","친구들과"]' AS JSON), TRUE, 42),
    ('BLIND_DATE', 'PURPOSE', '소개팅', CAST('["소개팅","첫 만남","소개팅 장소"]' AS JSON), TRUE, 43),
    ('SOLO', 'PURPOSE', '혼자', CAST('["혼자","혼자 가기 좋은","혼자서"]' AS JSON), TRUE, 44),
    ('SOLO_DINING', 'PURPOSE', '혼밥', CAST('["혼밥","혼자 밥","혼자 먹기 좋은"]' AS JSON), TRUE, 45),
    ('SOLO_CAFE', 'PURPOSE', '혼카페', CAST('["혼카페","혼자 카페","혼자 가기 좋은 카페"]' AS JSON), TRUE, 46),
    ('WORK', 'PURPOSE', '작업', CAST('["작업","작업하기 좋은","작업 카페","노트북"]' AS JSON), TRUE, 47),
    ('STUDY', 'PURPOSE', '공부', CAST('["공부","공부하기 좋은","스터디","공부 카페"]' AS JSON), TRUE, 48),
    ('GOOD_FOR_CONVERSATION', 'PURPOSE', '대화하기 좋은', CAST('["대화하기 좋은","이야기하기 좋은","얘기하기 좋은"]' AS JSON), TRUE, 49),
    ('READING', 'PURPOSE', '독서', CAST('["독서","책 읽기 좋은","책 읽기","북카페"]' AS JSON), TRUE, 50),
    ('ANNIVERSARY', 'PURPOSE', '기념일', CAST('["기념일","특별한 날","anniversary"]' AS JSON), TRUE, 51),
    ('BIRTHDAY', 'PURPOSE', '생일', CAST('["생일","생일파티","생일 모임","birthday"]' AS JSON), TRUE, 52),
    ('FAMILY', 'PURPOSE', '가족모임', CAST('["가족 모임","가족과","부모님과","가족 식사"]' AS JSON), TRUE, 53),
    ('COMPANY_DINNER', 'PURPOSE', '회식', CAST('["회식","단체 회식","직장 모임"]' AS JSON), TRUE, 54),
    ('FRIEND_GATHERING', 'PURPOSE', '친구모임', CAST('["친구 모임","친구들과","친구랑","친구와"]' AS JSON), TRUE, 55),
    ('PET_FRIENDLY', 'PURPOSE', '반려동물', CAST('["애견동반","반려동물 동반","강아지 동반","펫프렌들리"]' AS JSON), TRUE, 56),
    ('WITH_KIDS', 'PURPOSE', '아이와', CAST('["아이와","아이랑","아기랑","아이 동반"]' AS JSON), TRUE, 57),
    ('OUTING', 'PURPOSE', '나들이', CAST('["나들이","주말 나들이","산책 코스","주말에 가기 좋은"]' AS JSON), TRUE, 58),
    ('TRAVEL', 'PURPOSE', '여행', CAST('["여행","여행 코스","여행지","여행 중"]' AS JSON), TRUE, 59),
    ('DRIVE', 'PURPOSE', '드라이브', CAST('["드라이브","드라이브 코스","차 타고 가기 좋은"]' AS JSON), TRUE, 60),
    ('HIDDEN_GEM', 'EXPERIENCE', '숨은명소', CAST('["숨은 명소","숨겨진","아는 사람만","잘 알려지지 않은"]' AS JSON), TRUE, 61),
    ('HOT_PLACE', 'EXPERIENCE', '핫플', CAST('["핫플","핫플레이스","요즘 핫한","인기 많은"]' AS JSON), TRUE, 62),
    ('NEW_OPENING', 'EXPERIENCE', '신상', CAST('["신상","새로 생긴","신규 오픈","새로 오픈"]' AS JSON), TRUE, 63),
    ('LOCAL', 'EXPERIENCE', '로컬', CAST('["로컬","현지인 맛집","동네 맛집","현지인 추천"]' AS JSON), TRUE, 64),
    ('WAITING', 'EXPERIENCE', '웨이팅', CAST('["웨이팅","대기","줄 서서","대기시간"]' AS JSON), TRUE, 65),
    ('RESERVATION_REQUIRED', 'EXPERIENCE', '예약필수', CAST('["예약 필수","예약해야","사전 예약","예약 추천"]' AS JSON), TRUE, 66),
    ('RESERVATION_AVAILABLE', 'EXPERIENCE', '예약가능', CAST('["예약 가능","예약할 수","네이버 예약","캐치테이블"]' AS JSON), TRUE, 67),
    ('GOOD_VALUE', 'EXPERIENCE', '가성비', CAST('["가성비","가격 대비","합리적인 가격","가격이 착한"]' AS JSON), TRUE, 68),
    ('UNIQUE', 'EXPERIENCE', '특별한', CAST('["특별한","색다른","이색적인","이색"]' AS JSON), TRUE, 69),
    ('PHOTOGENIC', 'EXPERIENCE', '사진찍기 좋은', CAST('["사진 찍기 좋은","사진 맛집","인생샷","사진 잘 나오는"]' AS JSON), TRUE, 70),
    ('REVISIT', 'EXPERIENCE', '재방문', CAST('["재방문","또 가고 싶은","다시 가고 싶은","또 갈"]' AS JSON), TRUE, 71),
    ('LONG_ESTABLISHED', 'EXPERIENCE', '오래된', CAST('["오래된","오래된 가게","오래된 곳","오랜 역사의"]' AS JSON), TRUE, 72),
    ('OLD_SCHOOL', 'EXPERIENCE', '노포', CAST('["노포","오래된 맛집","노포 맛집","전통 있는"]' AS JSON), TRUE, 73),
    ('FAMOUS', 'EXPERIENCE', '유명한', CAST('["유명한","유명 맛집","소문난","잘 알려진"]' AS JSON), TRUE, 74),
    ('FRIENDLY', 'EXPERIENCE', '친절한', CAST('["친절한","친절하시고","친절해서","서비스 친절"]' AS JSON), TRUE, 75),
    ('RELAXED', 'EXPERIENCE', '여유로운', CAST('["여유로운","여유 있게","여유로운 분위기","느긋한"]' AS JSON), TRUE, 76),
    ('CROWDED', 'EXPERIENCE', '북적이는', CAST('["북적이는","사람 많은","북적북적","붐비는"]' AS JSON), TRUE, 77),
    ('ACCESSIBLE', 'EXPERIENCE', '접근성 좋은', CAST('["역 근처","역에서 가까운","접근성 좋은","역세권"]' AS JSON), TRUE, 78),
    ('PARKING', 'EXPERIENCE', '주차가능', CAST('["주차 가능","주차장","무료 주차","주차할 수"]' AS JSON), TRUE, 79),
    ('LATE_NIGHT', 'EXPERIENCE', '심야', CAST('["늦게까지","늦은 시간","심야","밤늦게"]' AS JSON), TRUE, 80),
    ('BRUNCH', 'FOOD_AND_BEVERAGE', '브런치', CAST('["브런치","브런치 맛집","브런치 카페"]' AS JSON), TRUE, 81),
    ('BAKERY', 'FOOD_AND_BEVERAGE', '베이커리', CAST('["베이커리","빵집","빵 맛집","제과"]' AS JSON), TRUE, 82),
    ('DESSERT', 'FOOD_AND_BEVERAGE', '디저트', CAST('["디저트","디저트 맛집","디저트 카페"]' AS JSON), TRUE, 83),
    ('COFFEE', 'FOOD_AND_BEVERAGE', '커피', CAST('["커피 맛집","원두","핸드드립","커피가 맛있는"]' AS JSON), TRUE, 84),
    ('CAKE', 'FOOD_AND_BEVERAGE', '케이크', CAST('["케이크","케이크 맛집","홀케이크","조각 케이크"]' AS JSON), TRUE, 85),
    ('WINE', 'FOOD_AND_BEVERAGE', '와인', CAST('["와인","와인바","내추럴 와인","와인 페어링"]' AS JSON), TRUE, 86),
    ('COCKTAIL', 'FOOD_AND_BEVERAGE', '칵테일', CAST('["칵테일","칵테일바","바텐딩"]' AS JSON), TRUE, 87),
    ('WHISKEY', 'FOOD_AND_BEVERAGE', '위스키', CAST('["위스키","위스키바","몰트","싱글몰트"]' AS JSON), TRUE, 88),
    ('TRADITIONAL_LIQUOR', 'FOOD_AND_BEVERAGE', '전통주', CAST('["전통주","막걸리","약주","우리술"]' AS JSON), TRUE, 89),
    ('VEGAN', 'FOOD_AND_BEVERAGE', '비건', CAST('["비건","vegan","비건 메뉴","식물성"]' AS JSON), TRUE, 90),
    ('VEGETARIAN', 'FOOD_AND_BEVERAGE', '채식', CAST('["채식","베지테리언","채식 메뉴","vegetarian"]' AS JSON), TRUE, 91),
    ('FINE_DINING', 'FOOD_AND_BEVERAGE', '파인다이닝', CAST('["파인다이닝","fine dining","파인 다이닝"]' AS JSON), TRUE, 92),
    ('COURSE_MEAL', 'FOOD_AND_BEVERAGE', '코스요리', CAST('["코스요리","코스 메뉴","코스로","course"]' AS JSON), TRUE, 93),
    ('OMAKASE', 'FOOD_AND_BEVERAGE', '오마카세', CAST('["오마카세","맡김차림","스시 오마카세"]' AS JSON), TRUE, 94),
    ('DINING_BAR', 'FOOD_AND_BEVERAGE', '다이닝바', CAST('["다이닝바","다이닝 바","음식과 술"]' AS JSON), TRUE, 95),
    ('PUB', 'FOOD_AND_BEVERAGE', '펍', CAST('["펍","pub","생맥주","맥주집"]' AS JSON), TRUE, 96),
    ('TEA_ROOM', 'FOOD_AND_BEVERAGE', '티룸', CAST('["티룸","티하우스","차 전문점","티 코스"]' AS JSON), TRUE, 97),
    ('GOOD_FOOD', 'FOOD_AND_BEVERAGE', '맛집', CAST('["맛집","맛있는 곳","맛있었던","맛있어요"]' AS JSON), TRUE, 98),
    ('BAR', 'FOOD_AND_BEVERAGE', '술집', CAST('["술집","한잔하기 좋은","술 마시기 좋은"]' AS JSON), TRUE, 99),
    ('CAFE', 'FOOD_AND_BEVERAGE', '카페', CAST('["카페","coffee shop","커피숍","카페 추천"]' AS JSON), TRUE, 100);
