apiVersion: 1

deleteContactPoints:
  - orgId: 1
    uid: slack_nook_alerts

contactPoints:
  - orgId: 1
    name: slack-nook-alerts-v2
    receivers:
      - uid: slack_nook_alerts_v2
        type: slack
        disableResolveMessage: false
        settings:
          url: $SLACK_ALERT_WEBHOOK_URL
          title: |
            {{ if eq .Status "firing" }}[FIRING]{{ else }}[RESOLVED]{{ end }} {{ .CommonLabels.alertname }}
          text: |
            {{ range .Alerts }}
            *{{ .Labels.env }} {{ .Labels.service }}* - {{ .Labels.severity }}
            {{ .Annotations.summary }}
            {{ .Annotations.description }}
            {{ .GeneratorURL }}
            {{ end }}
