import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, LinearProgress, MenuItem, Stack, TextField, Typography } from "@mui/material";
import { useEffect, useMemo, useState } from "react";
import type React from "react";
import { api } from "./api";

type Provider = { provider: string; calls: number; failures: number; units: number; estimatedCostUsd?: number; estimatedCostKrw?: number; pricingStatus: string };
type Event = { id: number; provider: string; operation: string; sku: string; status: string; durationMs: number; httpStatus?: number; failureType?: string; estimatedCostUsd?: number; estimatedCostKrw?: number; occurredAt: string };
type Summary = { totalCalls: number; failedCalls: number; estimatedCostUsd?: number; estimatedCostKrw?: number; unpricedCalls: number; providers: Provider[]; recentEvents: Event[] };
type OverviewProvider = { provider: string; displayName: string; category: string; purpose: string; runtimes: string[]; credentialConfigured: boolean; operationalState: string; stateReason: string; policy: string; calls: number; failures: number; estimatedCostUsd?: number; estimatedCostKrw?: number; pricingStatus: string; lastCalledAt?: string; lastFailureAt?: string };
type Overview = { providers: OverviewProvider[] };
type SkuLimit = { id: number; limitType: string; monthlyLimit: number; currentValue: number; utilizationPercent: number; enabled: boolean; reachedThresholds: number[] };
type SkuUsage = { provider: string; sku: string; unitType: string; calls: number; freeMonthlyUnits: number; billableUnits: number; freeQuotaPercent?: number; estimatedCostUsd?: number; pricingStatus: string; sourceUnitPrice?: number; priceUnitSize?: number; sourceUrl?: string; limits: SkuLimit[] };
type SkuOverview = { skus: SkuUsage[] };
type BillingSku = { sku: string; usageUnits: number; actualCostUsd: number; source: string; sourceUpdatedAt: string };
type BillingProvider = { provider: string; status: string; lastAttemptedAt?: string; lastSucceededAt?: string; errorMessage?: string; usageUnits: number; actualCostUsd: number; source?: string; skus: BillingSku[] };
type BillingOverview = { providers: BillingProvider[] };
const krw = new Intl.NumberFormat("ko-KR", { style: "currency", currency: "KRW", maximumFractionDigits: 0 });
const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 4 });
const fmt = new Intl.NumberFormat("ko-KR");

export function ExternalProviderUsagePage() {
  const currentMonth = useMemo(() => new Date().toISOString().slice(0, 7), []);
  const [month, setMonth] = useState(currentMonth); const [provider, setProvider] = useState("");
  const [overviewState, setOverviewState] = useState("ALL");
  const [reloadKey, setReloadKey] = useState(0);
  const [data, setData] = useState<Summary>(); const [overview, setOverview] = useState<Overview>(); const [skuData, setSkuData] = useState<SkuOverview>(); const [billing, setBilling] = useState<BillingOverview>(); const [error, setError] = useState("");
  useEffect(() => {
    const from = new Date(`${month}-01T00:00:00+09:00`); const to = new Date(from); to.setMonth(to.getMonth() + 1);
    const query = new URLSearchParams({ from: from.toISOString(), to: to.toISOString(), limit: "100" }); if (provider) query.set("provider", provider);
    const billingQuery = new URLSearchParams({ from: `${month}-01`, to: to.toISOString().slice(0, 10) });
    setData(undefined); setOverview(undefined); setSkuData(undefined); setBilling(undefined); setError("");
    Promise.all([api<Summary>(`/external-provider-usage?${query}`), api<Overview>(`/external-provider-usage/overview?${query}`), api<SkuOverview>(`/external-provider-usage/skus?${query}`), api<BillingOverview>(`/external-provider-usage/billing?${billingQuery}`)])
      .then(([usage, catalog, skus, actualBilling]) => { setData(usage); setOverview(catalog); setSkuData(skus); setBilling(actualBilling); })
      .catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "외부 API 현황을 불러오지 못했습니다."));
  }, [month, provider, reloadKey]);
  if (error) return <Alert severity="error">{error}</Alert>;
  if (!data || !overview || !skuData || !billing) return <Box sx={{ p: 5, textAlign: "center" }}><CircularProgress /></Box>;
  const providerOptions = overview.providers.map((item) => item.provider);
  const visibleOverview = overview.providers.filter((item) =>
    (!provider || item.provider === provider) && (overviewState === "ALL" || item.operationalState === overviewState));
  return <Stack spacing={3} sx={{ maxWidth: 1500 }}><Stack direction={{ xs: "column", md: "row" }} sx={{ justifyContent: "space-between", gap: 2 }}><Box><Typography variant="h4">외부 API 현황</Typography><Typography color="text.secondary">연동된 API, 실제 호출 정책과 기간별 사용량·비용을 함께 봅니다. 호출 이력이 없어도 표시됩니다.</Typography></Box><Stack direction="row" spacing={1}><TextField type="month" size="small" value={month} onChange={(e) => setMonth(e.target.value)} /><TextField select size="small" label="Provider" value={provider} onChange={(e) => setProvider(e.target.value)} sx={{ minWidth: 190 }}><MenuItem value="">전체</MenuItem>{providerOptions.map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Stack></Stack>
    <Card variant="outlined"><CardContent><Stack direction={{ xs: "column", md: "row" }} sx={{ justifyContent: "space-between", gap: 2, mb: 2 }}><Box><Typography variant="h6">연동·운영 오버뷰</Typography><Typography variant="body2" color="text.secondary">상태는 현재 runtime 설정과 credential 설정 여부를 기준으로 계산합니다.</Typography></Box><TextField select size="small" label="운영 상태" value={overviewState} onChange={(e) => setOverviewState(e.target.value)} sx={{ minWidth: 170 }}><MenuItem value="ALL">전체</MenuItem>{["ACTIVE", "FALLBACK", "STANDBY", "DISABLED", "MISCONFIGURED"].map((value) => <MenuItem key={value} value={value}>{stateLabel(value)}</MenuItem>)}</TextField></Stack><Box className="usage-table"><table><thead><tr>{["외부 API", "용도", "운영 상태", "호출 정책", "이번 달", "최근 상태"].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{visibleOverview.map((item) => <tr key={item.provider}><td><strong>{item.displayName}</strong><div className="mono-text"><small>{item.provider}</small></div><small>{item.runtimes.join(" · ")}</small></td><td><Chip size="small" variant="outlined" label={item.category} /><div>{item.purpose}</div></td><td><Chip size="small" label={stateLabel(item.operationalState)} color={stateColor(item.operationalState)} /><div><small>{item.stateReason}</small></div>{!item.credentialConfigured && <div><small>credential 누락</small></div>}</td><td><small>{item.policy}</small></td><td><strong>{fmt.format(item.calls)}회</strong><div><small>실패 {fmt.format(item.failures)} · {item.estimatedCostUsd == null ? "비용 —" : usd.format(item.estimatedCostUsd)}</small></div><div><small>{item.pricingStatus}</small></div></td><td><small>최근 호출 {dateOrDash(item.lastCalledAt)}</small><br /><small>최근 오류 {dateOrDash(item.lastFailureAt)}</small></td></tr>)}</tbody></table></Box></CardContent></Card>
    {data.unpricedCalls > 0 && <Alert severity="warning">공개 단가를 확정할 수 없거나 환율이 설정되지 않은 호출이 {fmt.format(data.unpricedCalls)}건 있습니다. 비용을 0원으로 간주하지 않습니다.</Alert>}
    <BillingTable billing={billing} />
    <Stack direction={{ xs: "column", md: "row" }} spacing={2}>{[["총 호출", fmt.format(data.totalCalls)], ["실패", `${fmt.format(data.failedCalls)}건 (${data.totalCalls ? (data.failedCalls / data.totalCalls * 100).toFixed(1) : "0.0"}%)`], ["예상 비용", data.estimatedCostUsd == null ? "미산정" : `${usd.format(data.estimatedCostUsd)}${data.estimatedCostKrw == null ? "" : ` · ${krw.format(data.estimatedCostKrw)}`}`], ["가격 미확정", `${fmt.format(data.unpricedCalls)}건`]].map(([label, value]) => <Card variant="outlined" sx={{ flex: 1 }} key={label}><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h5" sx={{ mt: 1 }}>{value}</Typography></CardContent></Card>)}</Stack>
    <SkuUsageTable skus={skuData.skus.filter((item) => !provider || item.provider === provider)} onSaved={() => setReloadKey((value) => value + 1)} />
    <UsageTable title="Provider별 집계" headers={["Provider", "호출", "실패", "사용량", "예상 비용", "가격 상태"]}>{data.providers.map((item) => <tr key={item.provider}><td className="mono-text">{item.provider}</td><td>{fmt.format(item.calls)}</td><td>{fmt.format(item.failures)}</td><td>{fmt.format(item.units)}</td><td>{item.estimatedCostUsd == null ? "—" : usd.format(item.estimatedCostUsd)}</td><td><Chip size="small" label={item.pricingStatus} color={item.estimatedCostUsd != null ? "success" : "warning"} /></td></tr>)}</UsageTable>
    <UsageTable title="최근 물리 요청" headers={["시각", "Provider", "Operation / SKU", "결과", "지연", "비용"]}>{data.recentEvents.map((event) => <tr key={event.id}><td>{new Date(event.occurredAt).toLocaleString("ko-KR")}</td><td className="mono-text">{event.provider}</td><td><div className="mono-text">{event.operation}</div><small>{event.sku}</small></td><td><Chip size="small" label={event.httpStatus ? `${event.status} · ${event.httpStatus}` : event.status} color={event.status === "SUCCEEDED" ? "success" : "error"} />{event.failureType && <div><small>{event.failureType}</small></div>}</td><td>{fmt.format(event.durationMs)}ms</td><td>{event.estimatedCostUsd == null ? "—" : usd.format(event.estimatedCostUsd)}</td></tr>)}</UsageTable>
  </Stack>;
}

function BillingTable({ billing }: { billing: BillingOverview }) {
  return <Card variant="outlined"><CardContent><Typography variant="h6">공식 빌링 사용량</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>공급자 공식 API에서 매시간 동기화한 계정 기준 비용입니다. 로컬 예상 비용보다 이 값을 우선합니다.</Typography><Box className="usage-table"><table><thead><tr>{["공급자 / SKU", "공급자 사용량", "실제 비용", "동기화 상태", "데이터 출처"].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{billing.providers.flatMap((item) => item.skus.length ? item.skus.map((sku, index) => <tr key={`${item.provider}:${sku.sku}`}><td><strong>{index === 0 ? item.provider : ""}</strong><div className="mono-text"><small>{sku.sku}</small></div></td><td>{number(sku.usageUnits)} runs</td><td><strong>{usd.format(sku.actualCostUsd)}</strong></td><td><Chip size="small" color={item.status === "SUCCEEDED" ? "success" : "error"} label={item.status} /><div><small>성공 {dateOrDash(item.lastSucceededAt)}</small></div>{item.errorMessage && <div><small>{item.errorMessage}</small></div>}</td><td><small>{sku.source}</small><div><small>관측 {dateOrDash(sku.sourceUpdatedAt)}</small></div></td></tr>) : [<tr key={item.provider}><td><strong>{item.provider}</strong></td><td>—</td><td>—</td><td><Chip size="small" label={item.status} /></td><td>{item.errorMessage ?? "아직 동기화되지 않음"}</td></tr>])}</tbody></table></Box></CardContent></Card>;
}

function stateLabel(state: string) { return ({ ACTIVE: "사용 중", FALLBACK: "Fallback", STANDBY: "대기", DISABLED: "비활성", MISCONFIGURED: "설정 누락" } as Record<string, string>)[state] ?? state; }
function stateColor(state: string): "success" | "info" | "warning" | "default" | "error" { const colors: Record<string, "success" | "info" | "warning" | "default" | "error"> = { ACTIVE: "success", FALLBACK: "info", STANDBY: "warning", DISABLED: "default", MISCONFIGURED: "error" }; return colors[state] ?? "default"; }
function dateOrDash(value?: string) { return value ? new Date(value).toLocaleString("ko-KR") : "—"; }

function SkuUsageTable({ skus, onSaved }: { skus: SkuUsage[]; onSaved: () => void }) {
  const [drafts, setDrafts] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(""); const [error, setError] = useState("");
  const save = async (item: SkuUsage, limitType: string, enabled = true) => {
    const key = `${item.provider}:${item.sku}:${limitType}`; const existing = item.limits.find((limit) => limit.limitType === limitType); const raw = drafts[key] ?? existing?.monthlyLimit.toString() ?? "";
    if (!raw || Number(raw) <= 0) { setError("상한은 0보다 큰 값이어야 합니다."); return; }
    setSaving(key); setError("");
    try { await api("/external-provider-usage/limits", { method: "PUT", body: JSON.stringify({ provider: item.provider, sku: item.sku, limitType, monthlyLimit: Number(raw), enabled }) }); onSaved(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "상한 저장에 실패했습니다."); }
    finally { setSaving(""); }
  };
  return <Card variant="outlined"><CardContent><Typography variant="h6">API·SKU별 사용량과 상한</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>무료 quota, 유료 구간과 월 상한을 비교합니다. 상한의 50%·80%·95%·100% 도달 시 Slack 알림 대상이 됩니다.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Box className="usage-table"><table><thead><tr>{["Provider / SKU", "사용량", "무료 quota", "예상 비용", "상한 소진율", "월 상한 설정"].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{skus.map((item) => <tr key={`${item.provider}:${item.sku}`}><td><strong>{item.provider}</strong><div className="mono-text"><small>{item.sku}</small></div><Chip size="small" variant="outlined" label={item.unitType} /></td><td><strong>{number(item.calls)}</strong><div><small>과금 대상 {number(item.billableUnits)}</small></div></td><td>{item.freeMonthlyUnits > 0 ? <><div>{number(item.calls)} / {number(item.freeMonthlyUnits)}</div><LinearProgress variant="determinate" value={Math.min(100, item.freeQuotaPercent ?? 0)} color={(item.freeQuotaPercent ?? 0) >= 100 ? "warning" : "primary"} /><small>{(item.freeQuotaPercent ?? 0).toFixed(1)}%</small></> : "무료 quota 없음"}</td><td><strong>{item.estimatedCostUsd == null ? "—" : usd.format(item.estimatedCostUsd)}</strong><div><small>{item.pricingStatus}</small></div></td><td>{item.limits.length ? item.limits.map((limit) => <Box key={limit.limitType} sx={{ mb: 1 }}><div><small>{limit.limitType}: {number(limit.currentValue)} / {number(limit.monthlyLimit)} {!limit.enabled && "· 알림 꺼짐"}</small></div><LinearProgress variant="determinate" value={Math.min(100, limit.utilizationPercent)} color={limit.utilizationPercent >= 100 ? "error" : limit.utilizationPercent >= 80 ? "warning" : "success"} /><small>{limit.utilizationPercent.toFixed(1)}% · 도달 {limit.reachedThresholds.join("/") || "—"}</small></Box>) : "설정 없음"}</td><td>{["CALLS", "COST_USD"].map((type) => { const key = `${item.provider}:${item.sku}:${type}`; const existing = item.limits.find((limit) => limit.limitType === type); return <Stack direction="row" spacing={1} key={type} sx={{ mb: 1 }}><TextField size="small" type="number" label={type === "CALLS" ? "호출 상한" : "USD 상한"} value={drafts[key] ?? existing?.monthlyLimit ?? ""} onChange={(event) => setDrafts({ ...drafts, [key]: event.target.value })} sx={{ width: 125 }} /><Button size="small" variant="outlined" disabled={saving === key} onClick={() => save(item, type)}>저장</Button>{existing && <Button size="small" color={existing.enabled ? "warning" : "success"} disabled={saving === key} onClick={() => save(item, type, !existing.enabled)}>{existing.enabled ? "알림 끄기" : "알림 켜기"}</Button>}</Stack>; })}</td></tr>)}</tbody></table></Box></CardContent></Card>;
}

function number(value: number) { return new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 4 }).format(value); }

function UsageTable({ title, headers, children }: { title: string; headers: string[]; children: React.ReactNode }) { return <Card variant="outlined"><CardContent><Typography variant="h6" sx={{ mb: 2 }}>{title}</Typography><Box className="usage-table"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></Box></CardContent></Card>; }
