global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: nook-ops

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
        labels:
          env: ops
          service: prometheus

  - job_name: nook-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 192.168.0.102:8080
        labels:
          env: dev
          service: nook-api

  - job_name: nook-api-live
    metrics_path: /actuator/prometheus
    scheme: https
    tls_config:
      server_name: api.everynook.co.kr
    relabel_configs:
      - target_label: job
        replacement: nook-api
    static_configs:
      - targets:
          - 192.168.0.216:443
        labels:
          env: live
          service: nook-api

  - job_name: nook-worker-dev
    metrics_path: /actuator/prometheus
    relabel_configs:
      - target_label: job
        replacement: nook-worker
    static_configs:
      - targets:
          - localhost:18081
        labels:
          env: dev
          service: nook-worker

  - job_name: nook-worker-live
    metrics_path: /actuator/prometheus
    relabel_configs:
      - target_label: job
        replacement: nook-worker
    static_configs:
      - targets:
          - 192.168.0.216:18081
        labels:
          env: live
          service: nook-worker

  - job_name: node
    static_configs:
      - targets:
          - 192.168.0.102:9100
        labels:
          env: dev
          service: nook-dev
      - targets:
          - 192.168.0.216:9100
        labels:
          env: live
          service: nook-live

  - job_name: mysql
    static_configs:
      - targets:
          - 192.168.0.102:9104
        labels:
          env: dev
          service: nook-mysql
