logging:
  level:
    org.hibernate.SQL: debug

app:
  logging:
    http:
      body:
        request-enabled: ${HTTP_LOG_REQUEST_BODY_ENABLED:true}
        response-enabled: ${HTTP_LOG_RESPONSE_BODY_ENABLED:true}
