logging:
  level:
    org.every.nook.api: info

app:
  logging:
    http:
      body:
        request-enabled: ${HTTP_LOG_REQUEST_BODY_ENABLED:false}
        response-enabled: ${HTTP_LOG_RESPONSE_BODY_ENABLED:false}

nook:
  openapi:
    servers:
      - https://api.everynook.co.kr
